# JSON
set(JSON_LIB_FILE json.hpp)
set(JSON_LIB_LINK https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/${JSON_LIB_FILE})
set(JSON_LIB_PATH ${PROJECT_SOURCE_DIR}/lib/${JSON_LIB_FILE})
if (NOT EXISTS ${JSON_LIB_PATH})
    file(DOWNLOAD ${JSON_LIB_LINK} ${JSON_LIB_PATH} STATUS JSON_LIB_DL_STATUS)
    list(GET JSON_LIB_DL_STATUS 0 JSON_LIB_DL_RES)
    list(GET JSON_LIB_DL_STATUS 1 JSON_LIB_DL_MSG)
    if (${JSON_LIB_DL_RES} EQUAL 0)
    else()
        file(REMOVE ${JSON_LIB_PATH})
        message(FATAL_ERROR ${JSON_LIB_DL_MSG})
    endif()
endif()
